// Generated by CoffeeScript 1.8.0
(function() {
  var query, query_again, querying;

  window.populate_accounts = function(id) {
    var $el, a, account, _i, _len, _results;
    $el = $(id);
    _results = [];
    for (_i = 0, _len = accounts.length; _i < _len; _i++) {
      account = accounts[_i];
      a = $('<a role="button" class="btn btn-default active" />');
      a.text(account.name);
      a.append('<br/>');
      a.append($('<span class="small">').text(account.number));
      a.data({
        id: account.id
      });
      _results.push($el.append(a));
    }
    return _results;
  };

  querying = false;

  query_again = false;

  query = function() {
    var data, req;
    if (querying) {
      query_again = true;
      return;
    }
    querying = true;
    query_again = false;
    data = {
      order: $('#order').val(),
      date_start: $('#date-start').val(),
      date_end: $('#date-end').val(),
      search: $('#text').val(),
      type: $('#type .active').data('type'),
      accounts: $('#account-buttons .active').map(function() {
        return $(this).data('id');
      }).toArray()
    };
    req = $.ajax({
      url: 'q/search.html',
      method: 'post',
      contentType: 'application/json; charset=UTF-8',
      dataType: 'html',
      data: JSON.stringify(data)
    });
    req.done(function(result) {
      return console.log(result);
    });
    req.fail(function() {});
    return req.always(function() {
      querying = false;
      if (query_again) {
        return query();
      }
    });
  };

  query = _.debounce(query, 300);

  $(function() {
    var $accountButtons, $typeButtons, months, now;
    months = 'Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'.split(' ');
    now = new Date;
    $('#date-range input').val("" + (now.getDate()) + " " + months[now.getMonth()] + " " + (now.getFullYear()));
    $('.input-daterange').datepicker({
      format: "d M yyyy",
      startView: 2,
      todayBtn: 'linked',
      autoclose: true
    });
    $accountButtons = $('#account-buttons a');
    $('#account-button-bulk').on('click', 'a', function(e) {
      var set;
      set = $(e.currentTarget).data('set');
      $accountButtons.toggleClass('active', set === 'on');
      return query();
    });
    $typeButtons = $('#type a');
    $('#type').on('click', 'a', function(e) {
      if ($(e.currentTarget).hasClass('active')) {
        return;
      }
      $typeButtons.each(function() {
        return $(this).toggleClass('active', this === e.currentTarget);
      });
      return query();
    });
    return query();
  });

}).call(this);

//# sourceMappingURL=main.js.map
