// Generated by CoffeeScript 1.12.7
(function() {
  var COLOURS, post, query, query_again, querying, setColour, setColours,
    slice = [].slice;

  COLOURS = 'white red yellow green cyan blue magenta'.split(' ');

  window.populate_accounts = function(id) {
    var $el, a, account, j, len, results;
    $el = $(id);
    results = [];
    for (j = 0, len = accounts.length; j < len; j++) {
      account = accounts[j];
      a = $('<a role="button" class="btn btn-default active" />');
      a.text(account.name);
      a.append('<br/>');
      a.append($('<span class="small">').text(account.number));
      a.data({
        id: account.id
      });
      results.push($el.append(a));
    }
    return results;
  };

  post = function(page, data) {
    return $.ajax({
      url: "q/" + page,
      method: 'post',
      contentType: 'application/json; charset=UTF-8',
      dataType: page.match(/[^.]+$/)[0],
      data: JSON.stringify(data)
    });
  };

  querying = false;

  query_again = false;

  query = function() {
    var req;
    if (querying) {
      query_again = true;
      return;
    }
    querying = true;
    query_again = false;
    $('#content').html('One moment...');
    req = post('search.html', {
      order: $('#order').val(),
      date_start: $('#date-start').val(),
      date_end: $('#date-end').val(),
      search: $('#text').val(),
      type: $('#type .active').data('type'),
      accounts: $('#account-buttons .active').map(function() {
        return $(this).data('id');
      }).toArray(),
      colours: $('#colour .active').map(function() {
        return this.className.match(/colour-(\w+)/)[1];
      }).toArray()
    });
    req.done(function(result) {
      return $('#content').html(result);
    });
    req.fail(function() {
      return alert('Query failed');
    });
    return req.always(function() {
      querying = false;
      if (query_again) {
        return query();
      }
    });
  };

  query = _.debounce(query, 300);

  setColour = function(transactionId, colour) {
    return post('colour.json', {
      id: transactionId,
      colour: colour
    });
  };

  setColours = function(transactionIds, colour) {
    var op, rest, transactionId;
    transactionId = transactionIds[0], rest = 2 <= transactionIds.length ? slice.call(transactionIds, 1) : [];
    op = setColour(transactionId, colour);
    op.fail(function() {
      return alert('Something went wrong. Try reloading?');
    });
    return op.done(function() {
      var $tr;
      $tr = $("tr[data-id=" + transactionId + "]");
      if ($tr[0]) {
        $tr[0].className = $tr[0].className.replace(/colour-\w+/, "colour-" + colour);
      }
      if (rest[0]) {
        return setColours(rest, colour);
      }
    });
  };

  $(function() {
    var $accountButtons, $picker, $typeButtons, closePicker, i, k, months, range;
    months = 'Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'.split(' ');
    range = {
      end: new Date
    };
    range.end.setDate(1);
    while (range.end.getMonth() !== 6) {
      range.end.setMonth(range.end.getMonth() - 1);
    }
    range.start = new Date(range.end);
    range.start.setFullYear(range.start.getFullYear() - 1);
    range.end.setDate(range.end.getDate() - 1);
    for (k in range) {
      i = range[k];
      $("#date-" + k).val((i.getDate()) + " " + months[i.getMonth()] + " " + (i.getFullYear()));
    }
    $('.input-daterange').datepicker({
      format: "d M yyyy",
      startView: 2,
      todayBtn: 'linked',
      autoclose: true
    }).on('changeDate', query);
    $('#order').on('change', query);
    $('date-range').on('change', 'input', query);
    $('#text').on('change keyup', query);
    $('#colour').on('click', 'a', query);
    $accountButtons = $('#account-buttons a');
    $accountButtons.on('click', query);
    $('#account-button-bulk').on('click', 'a', function(e) {
      var set;
      set = $(e.currentTarget).data('set');
      $accountButtons.toggleClass('active', set === 'on');
      return query();
    });
    $typeButtons = $('#type a');
    $('#type').on('click', 'a', function(e) {
      if ($(e.currentTarget).hasClass('active')) {
        return;
      }
      $typeButtons.each(function() {
        return $(this).toggleClass('active', this === e.currentTarget);
      });
      return query();
    });
    $picker = null;
    $('body').on('click', function(e) {
      var target;
      target = e.currentTarget;
      if (!($picker && (target === $picker[0] || $picker.find(target)[0]))) {
        return closePicker();
      }
    });
    closePicker = function() {
      if ($picker) {
        $picker.remove();
      }
      return $picker = null;
    };
    $('#content').on('click', 'td.colour a.picker', function(e) {
      var $td, $tr, j, len;
      e.stopPropagation();
      closePicker();
      $tr = $(e.currentTarget).parents('tr').first();
      $td = $tr.find('td.colour');
      $picker = $('<ul class="colours">');
      for (j = 0, len = COLOURS.length; j < len; j++) {
        i = COLOURS[j];
        $picker.append($('<li>').addClass("colour-" + i).append('<a href="javascript:">'));
      }
      $picker.appendTo($td);
      return $picker.on('click', 'a', function(e) {
        var $li, colour, x;
        closePicker();
        $li = $(e.currentTarget).parents('li').first();
        colour = $li[0].className.match(/colour-(\w+)/)[1];
        if (e.shiftKey) {
          return setColours((function() {
            var l, len1, ref, results;
            ref = $tr.parent().children();
            results = [];
            for (l = 0, len1 = ref.length; l < len1; l++) {
              x = ref[l];
              results.push(x.dataset.id);
            }
            return results;
          })(), colour);
        } else {
          return setColours([$tr.data('id')], colour);
        }
      });
    });
    return query();
  });

}).call(this);

//# sourceMappingURL=main.js.map
